apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: shoutan-matching-frontend
spec:
  selector:
    matchLabels:
      app: shoutan-matching-frontend
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: shoutan-matching-frontend
        tier: frontend
    spec:
      containers:
      - name: shoutan-matching-frontend
        image: registry-vpc.cn-beijing.aliyuncs.com/shoutan/shoutan-matching-frontend:v0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: service-config
      imagePullSecrets:
      - name: aliyun-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoutan-matching-frontend
  labels:
    app: shoutan-matching-frontend
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: shoutan-matching-frontend
    tier: frontend
